// Code generated by tygo. DO NOT EDIT.

//////////
// source: guild.go

export interface GuildWire {
  id: string;
  name: string;
  icon: null | string;
  has_channel_with_user_access: boolean;
  has_channel_with_bot_access: boolean;
}
export interface GuildChannelWire {
  id: string;
  name: string;
  position: number /* int */;
  parent_id: null | string;
  type: number /* int */;
  user_access: boolean;
  user_permissions: string;
  bot_access: boolean;
  bot_permissions: string;
}
export interface GuildRoleWire {
  id: string;
  name: string;
  managed: boolean;
}
export interface GuildEmojiWire {
  id: string;
  name: string;
  available: boolean;
  animated: boolean;
  managed: boolean;
}
export interface GuildStickerWire {
  id: string;
  name: string;
  description: string;
  available: boolean;
  formant_type: number /* int */;
}

//////////
// source: magic.go

export interface GenerateMagicMessageRequestWire {
  base_data: null | string;
  prompt: string;
}
export interface GenerateMagicMessagePromptWire {
  type: string;
  text: string;
}
export interface GenerateMagicMessageResponseWire {
  data: string;
}

//////////
// source: message.go

export interface SavedMessageWire {
  id: string;
  owner_id: string;
  guild_id: null | string;
  updated_at: string /* RFC3339 */;
  name: string;
  description: null | string;
  data: Record<string, any> | null;
}
export type SavedMessageListResponseWire = SavedMessageWire[];
export type SavedMessageGetResponseWire = SavedMessageWire;
export interface SavedMessageCreateRequestWire {
  name: string;
  description: null | string;
  data: Record<string, any> | null;
}
export type SavedMessageCreateResponseWire = SavedMessageWire;
export interface SavedMessageUpdateRequestWire {
  name: string;
  description: null | string;
  data: Record<string, any> | null;
}
export type SavedMessageUpdateResponseWire = SavedMessageWire;
export interface SavedMessageDeleteResponseWire {
}
export interface MessageSendToWebhookRequestWire {
  webhook_id: string;
  webhook_token: string;
  thread_id: null | string;
  message_id: null | string;
  data: Record<string, any> | null;
  attachments: MessageSendRequestAttachmentWire[];
}
export interface MessageSendToChannelRequestWire {
  guild_id: string;
  channel_id: string;
  message_id: null | string;
  data: Record<string, any> | null;
  attachments: MessageSendRequestAttachmentWire[];
}
export interface MessageSendRequestAttachmentWire {
  name: string;
  description: null | string;
  data_url: string;
}
export interface MessageSendResponseWire {
  message_id: string;
}

//////////
// source: user.go

export interface UserWire {
  id: string;
  name: string;
  discriminator: string;
  avatar: null | string;
}
