// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistant_prompts.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssistantPromptsSince = `-- name: CountAssistantPromptsSince :one
SELECT
    COUNT(*) FILTER (WHERE edited)::int AS edited,
    COUNT(*)::int AS total
FROM assistant_prompts WHERE guild_id = $1 AND created_at >= $2
`

type CountAssistantPromptsSinceParams struct {
	GuildID string
	StartAt pgtype.Timestamp
}

type CountAssistantPromptsSinceRow struct {
	Edited int32
	Total  int32
}

func (q *Queries) CountAssistantPromptsSince(ctx context.Context, arg CountAssistantPromptsSinceParams) (CountAssistantPromptsSinceRow, error) {
	row := q.db.QueryRow(ctx, countAssistantPromptsSince, arg.GuildID, arg.StartAt)
	var i CountAssistantPromptsSinceRow
	err := row.Scan(&i.Edited, &i.Total)
	return i, err
}

const deleteAssistantPrompt = `-- name: DeleteAssistantPrompt :exec
DELETE FROM assistant_prompts WHERE id = $1 AND guild_id = $2
`

type DeleteAssistantPromptParams struct {
	ID      string
	GuildID string
}

func (q *Queries) DeleteAssistantPrompt(ctx context.Context, arg DeleteAssistantPromptParams) error {
	_, err := q.db.Exec(ctx, deleteAssistantPrompt, arg.ID, arg.GuildID)
	return err
}

const finishAssistantPrompt = `-- name: FinishAssistantPrompt :exec
UPDATE assistant_prompts SET
    edited = $1,
    rounds = $2,
    input_tokens = $3,
    cached_input_tokens = $4,
    output_tokens = $5,
    updated_at = $6
WHERE id = $7 AND guild_id = $8
`

type FinishAssistantPromptParams struct {
	Edited            bool
	Rounds            int32
	InputTokens       int32
	CachedInputTokens int32
	OutputTokens      int32
	UpdatedAt         pgtype.Timestamp
	ID                string
	GuildID           string
}

func (q *Queries) FinishAssistantPrompt(ctx context.Context, arg FinishAssistantPromptParams) error {
	_, err := q.db.Exec(ctx, finishAssistantPrompt,
		arg.Edited,
		arg.Rounds,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.UpdatedAt,
		arg.ID,
		arg.GuildID,
	)
	return err
}

const insertAssistantPrompt = `-- name: InsertAssistantPrompt :exec
INSERT INTO assistant_prompts (
    id,
    guild_id,
    user_id,
    model,
    prompt,
    edited,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertAssistantPromptParams struct {
	ID        string
	GuildID   string
	UserID    string
	Model     string
	Prompt    string
	Edited    bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) InsertAssistantPrompt(ctx context.Context, arg InsertAssistantPromptParams) error {
	_, err := q.db.Exec(ctx, insertAssistantPrompt,
		arg.ID,
		arg.GuildID,
		arg.UserID,
		arg.Model,
		arg.Prompt,
		arg.Edited,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
