// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistant_prompts.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAssistantPromptUsage = `-- name: AddAssistantPromptUsage :exec
UPDATE assistant_prompts SET
    edited = edited AND $1,
    input_tokens = input_tokens + $2,
    cached_input_tokens = cached_input_tokens + $3,
    output_tokens = output_tokens + $4,
    updated_at = $5
WHERE id = $6 AND guild_id = $7
`

type AddAssistantPromptUsageParams struct {
	Edited            bool
	InputTokens       int32
	CachedInputTokens int32
	OutputTokens      int32
	UpdatedAt         pgtype.Timestamp
	ID                string
	GuildID           string
}

// A prompt can only become unedited, when its first answer doesn't change the message.
func (q *Queries) AddAssistantPromptUsage(ctx context.Context, arg AddAssistantPromptUsageParams) error {
	_, err := q.db.Exec(ctx, addAssistantPromptUsage,
		arg.Edited,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.UpdatedAt,
		arg.ID,
		arg.GuildID,
	)
	return err
}

const countAssistantPromptsSince = `-- name: CountAssistantPromptsSince :one
SELECT
    COUNT(*) FILTER (WHERE edited)::int AS edited,
    COUNT(*)::int AS total
FROM assistant_prompts WHERE guild_id = $1 AND created_at >= $2
`

type CountAssistantPromptsSinceParams struct {
	GuildID string
	StartAt pgtype.Timestamp
}

type CountAssistantPromptsSinceRow struct {
	Edited int32
	Total  int32
}

func (q *Queries) CountAssistantPromptsSince(ctx context.Context, arg CountAssistantPromptsSinceParams) (CountAssistantPromptsSinceRow, error) {
	row := q.db.QueryRow(ctx, countAssistantPromptsSince, arg.GuildID, arg.StartAt)
	var i CountAssistantPromptsSinceRow
	err := row.Scan(&i.Edited, &i.Total)
	return i, err
}

const deleteAssistantPrompt = `-- name: DeleteAssistantPrompt :exec
DELETE FROM assistant_prompts WHERE id = $1 AND guild_id = $2
`

type DeleteAssistantPromptParams struct {
	ID      string
	GuildID string
}

func (q *Queries) DeleteAssistantPrompt(ctx context.Context, arg DeleteAssistantPromptParams) error {
	_, err := q.db.Exec(ctx, deleteAssistantPrompt, arg.ID, arg.GuildID)
	return err
}

const getAssistantPrompt = `-- name: GetAssistantPrompt :one
SELECT id, guild_id, user_id, model, prompt, edited, rounds, input_tokens, cached_input_tokens, output_tokens, created_at, updated_at FROM assistant_prompts WHERE id = $1 AND guild_id = $2
`

type GetAssistantPromptParams struct {
	ID      string
	GuildID string
}

func (q *Queries) GetAssistantPrompt(ctx context.Context, arg GetAssistantPromptParams) (AssistantPrompt, error) {
	row := q.db.QueryRow(ctx, getAssistantPrompt, arg.ID, arg.GuildID)
	var i AssistantPrompt
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.UserID,
		&i.Model,
		&i.Prompt,
		&i.Edited,
		&i.Rounds,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssistantPrompt = `-- name: InsertAssistantPrompt :exec
INSERT INTO assistant_prompts (
    id,
    guild_id,
    user_id,
    model,
    prompt,
    edited,
    rounds,
    input_tokens,
    cached_input_tokens,
    output_tokens,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type InsertAssistantPromptParams struct {
	ID                string
	GuildID           string
	UserID            string
	Model             string
	Prompt            string
	Edited            bool
	Rounds            int32
	InputTokens       int32
	CachedInputTokens int32
	OutputTokens      int32
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

func (q *Queries) InsertAssistantPrompt(ctx context.Context, arg InsertAssistantPromptParams) error {
	_, err := q.db.Exec(ctx, insertAssistantPrompt,
		arg.ID,
		arg.GuildID,
		arg.UserID,
		arg.Model,
		arg.Prompt,
		arg.Edited,
		arg.Rounds,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const startAssistantPromptRound = `-- name: StartAssistantPromptRound :execrows
UPDATE assistant_prompts SET
    rounds = rounds + 1,
    updated_at = $1
WHERE id = $2 AND guild_id = $3 AND rounds < $4
`

type StartAssistantPromptRoundParams struct {
	UpdatedAt pgtype.Timestamp
	ID        string
	GuildID   string
	MaxRounds int32
}

func (q *Queries) StartAssistantPromptRound(ctx context.Context, arg StartAssistantPromptRoundParams) (int64, error) {
	result, err := q.db.Exec(ctx, startAssistantPromptRound,
		arg.UpdatedAt,
		arg.ID,
		arg.GuildID,
		arg.MaxRounds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
