// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guilds.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGuilds = `-- name: GetGuilds :many
SELECT id, name, icon, owner_id, joined_at, left_at, updated_at FROM guilds WHERE id = ANY($1::bigint[]) AND left_at IS NULL
`

func (q *Queries) GetGuilds(ctx context.Context, dollar_1 []int64) ([]Guild, error) {
	rows, err := q.db.Query(ctx, getGuilds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guild
	for rows.Next() {
		var i Guild
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.OwnerID,
			&i.JoinedAt,
			&i.LeftAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGuildLeft = `-- name: MarkGuildLeft :exec
UPDATE guilds SET left_at = $2, updated_at = $2 WHERE id = $1
`

type MarkGuildLeftParams struct {
	ID     int64
	LeftAt pgtype.Timestamp
}

func (q *Queries) MarkGuildLeft(ctx context.Context, arg MarkGuildLeftParams) error {
	_, err := q.db.Exec(ctx, markGuildLeft, arg.ID, arg.LeftAt)
	return err
}

const markGuildsLeftOnShard = `-- name: MarkGuildsLeftOnShard :exec
UPDATE guilds SET left_at = $1, updated_at = $1
WHERE left_at IS NULL
  AND (id >> 22) % $2::bigint = $3::bigint
  AND updated_at < $1
  AND NOT (id = ANY($4::bigint[]))
`

type MarkGuildsLeftOnShardParams struct {
	Now        pgtype.Timestamp
	ShardCount int64
	ShardID    int64
	KeepIds    []int64
}

// Marks every guild on the shard that isn't in keep_ids as left. Rows written since the ready
// time are guilds joined while this ran, so they are skipped.
func (q *Queries) MarkGuildsLeftOnShard(ctx context.Context, arg MarkGuildsLeftOnShardParams) error {
	_, err := q.db.Exec(ctx, markGuildsLeftOnShard,
		arg.Now,
		arg.ShardCount,
		arg.ShardID,
		arg.KeepIds,
	)
	return err
}
