// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_message_versions.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldSavedMessageVersions = `-- name: DeleteOldSavedMessageVersions :exec
DELETE FROM saved_message_versions WHERE saved_message_versions.id IN (
    SELECT old.id FROM saved_message_versions old WHERE old.saved_message_id = $1 ORDER BY old.created_at DESC, old.id DESC OFFSET $2
)
`

type DeleteOldSavedMessageVersionsParams struct {
	SavedMessageID string
	KeepCount      int32
}

func (q *Queries) DeleteOldSavedMessageVersions(ctx context.Context, arg DeleteOldSavedMessageVersionsParams) error {
	_, err := q.db.Exec(ctx, deleteOldSavedMessageVersions, arg.SavedMessageID, arg.KeepCount)
	return err
}

const getSavedMessageVersionForCreator = `-- name: GetSavedMessageVersionForCreator :one
SELECT saved_message_versions.id, saved_message_versions.saved_message_id, saved_message_versions.created_at, saved_message_versions.name, saved_message_versions.data FROM saved_message_versions
JOIN saved_messages ON saved_messages.id = saved_message_versions.saved_message_id
WHERE saved_message_versions.id = $1 AND saved_message_versions.saved_message_id = $2 AND saved_messages.creator_id = $3 AND saved_messages.guild_id IS NULL
`

type GetSavedMessageVersionForCreatorParams struct {
	ID             string
	SavedMessageID string
	CreatorID      string
}

func (q *Queries) GetSavedMessageVersionForCreator(ctx context.Context, arg GetSavedMessageVersionForCreatorParams) (SavedMessageVersion, error) {
	row := q.db.QueryRow(ctx, getSavedMessageVersionForCreator, arg.ID, arg.SavedMessageID, arg.CreatorID)
	var i SavedMessageVersion
	err := row.Scan(
		&i.ID,
		&i.SavedMessageID,
		&i.CreatedAt,
		&i.Name,
		&i.Data,
	)
	return i, err
}

const getSavedMessageVersionForGuild = `-- name: GetSavedMessageVersionForGuild :one
SELECT saved_message_versions.id, saved_message_versions.saved_message_id, saved_message_versions.created_at, saved_message_versions.name, saved_message_versions.data FROM saved_message_versions
JOIN saved_messages ON saved_messages.id = saved_message_versions.saved_message_id
WHERE saved_message_versions.id = $1 AND saved_message_versions.saved_message_id = $2 AND saved_messages.guild_id = $3
`

type GetSavedMessageVersionForGuildParams struct {
	ID             string
	SavedMessageID string
	GuildID        pgtype.Text
}

func (q *Queries) GetSavedMessageVersionForGuild(ctx context.Context, arg GetSavedMessageVersionForGuildParams) (SavedMessageVersion, error) {
	row := q.db.QueryRow(ctx, getSavedMessageVersionForGuild, arg.ID, arg.SavedMessageID, arg.GuildID)
	var i SavedMessageVersion
	err := row.Scan(
		&i.ID,
		&i.SavedMessageID,
		&i.CreatedAt,
		&i.Name,
		&i.Data,
	)
	return i, err
}

const getSavedMessageVersionsForCreator = `-- name: GetSavedMessageVersionsForCreator :many
SELECT saved_message_versions.id, saved_message_versions.created_at, saved_message_versions.name FROM saved_message_versions
JOIN saved_messages ON saved_messages.id = saved_message_versions.saved_message_id
WHERE saved_message_versions.saved_message_id = $1 AND saved_messages.creator_id = $2 AND saved_messages.guild_id IS NULL
ORDER BY saved_message_versions.created_at DESC, saved_message_versions.id DESC LIMIT $3
`

type GetSavedMessageVersionsForCreatorParams struct {
	SavedMessageID string
	CreatorID      string
	MaxCount       int32
}

type GetSavedMessageVersionsForCreatorRow struct {
	ID        string
	CreatedAt pgtype.Timestamp
	Name      string
}

func (q *Queries) GetSavedMessageVersionsForCreator(ctx context.Context, arg GetSavedMessageVersionsForCreatorParams) ([]GetSavedMessageVersionsForCreatorRow, error) {
	rows, err := q.db.Query(ctx, getSavedMessageVersionsForCreator, arg.SavedMessageID, arg.CreatorID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavedMessageVersionsForCreatorRow
	for rows.Next() {
		var i GetSavedMessageVersionsForCreatorRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedMessageVersionsForGuild = `-- name: GetSavedMessageVersionsForGuild :many
SELECT saved_message_versions.id, saved_message_versions.created_at, saved_message_versions.name FROM saved_message_versions
JOIN saved_messages ON saved_messages.id = saved_message_versions.saved_message_id
WHERE saved_message_versions.saved_message_id = $1 AND saved_messages.guild_id = $2
ORDER BY saved_message_versions.created_at DESC, saved_message_versions.id DESC LIMIT $3
`

type GetSavedMessageVersionsForGuildParams struct {
	SavedMessageID string
	GuildID        pgtype.Text
	MaxCount       int32
}

type GetSavedMessageVersionsForGuildRow struct {
	ID        string
	CreatedAt pgtype.Timestamp
	Name      string
}

func (q *Queries) GetSavedMessageVersionsForGuild(ctx context.Context, arg GetSavedMessageVersionsForGuildParams) ([]GetSavedMessageVersionsForGuildRow, error) {
	rows, err := q.db.Query(ctx, getSavedMessageVersionsForGuild, arg.SavedMessageID, arg.GuildID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavedMessageVersionsForGuildRow
	for rows.Next() {
		var i GetSavedMessageVersionsForGuildRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSavedMessageVersionForCreator = `-- name: InsertSavedMessageVersionForCreator :execrows
INSERT INTO saved_message_versions (id, saved_message_id, created_at, name, data)
SELECT $1, saved_messages.id, saved_messages.updated_at, saved_messages.name, saved_messages.data FROM saved_messages
WHERE saved_messages.id = $2 AND saved_messages.creator_id = $3 AND saved_messages.guild_id IS NULL AND saved_messages.data <> $4::jsonb
FOR UPDATE OF saved_messages
`

type InsertSavedMessageVersionForCreatorParams struct {
	ID             string
	SavedMessageID string
	CreatorID      string
	NewData        []byte
}

func (q *Queries) InsertSavedMessageVersionForCreator(ctx context.Context, arg InsertSavedMessageVersionForCreatorParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSavedMessageVersionForCreator,
		arg.ID,
		arg.SavedMessageID,
		arg.CreatorID,
		arg.NewData,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSavedMessageVersionForGuild = `-- name: InsertSavedMessageVersionForGuild :execrows
INSERT INTO saved_message_versions (id, saved_message_id, created_at, name, data)
SELECT $1, saved_messages.id, saved_messages.updated_at, saved_messages.name, saved_messages.data FROM saved_messages
WHERE saved_messages.id = $2 AND saved_messages.guild_id = $3 AND saved_messages.data <> $4::jsonb
FOR UPDATE OF saved_messages
`

type InsertSavedMessageVersionForGuildParams struct {
	ID             string
	SavedMessageID string
	GuildID        pgtype.Text
	NewData        []byte
}

func (q *Queries) InsertSavedMessageVersionForGuild(ctx context.Context, arg InsertSavedMessageVersionForGuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSavedMessageVersionForGuild,
		arg.ID,
		arg.SavedMessageID,
		arg.GuildID,
		arg.NewData,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
