// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_messages.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScheduledMessages = `-- name: CountScheduledMessages :one
SELECT COUNT(*) FROM scheduled_messages WHERE guild_id = $1
`

func (q *Queries) CountScheduledMessages(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduledMessages, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteScheduledMessage = `-- name: DeleteScheduledMessage :exec
DELETE FROM scheduled_messages WHERE id = $1 AND guild_id = $2
`

type DeleteScheduledMessageParams struct {
	ID      string
	GuildID string
}

func (q *Queries) DeleteScheduledMessage(ctx context.Context, arg DeleteScheduledMessageParams) error {
	_, err := q.db.Exec(ctx, deleteScheduledMessage, arg.ID, arg.GuildID)
	return err
}

const getDueScheduledMessages = `-- name: GetDueScheduledMessages :many
SELECT id, creator_id, guild_id, channel_id, message_id, saved_message_id, name, description, cron_expression, only_once, start_at, end_at, next_at, enabled, created_at, updated_at, cron_timezone, thread_name, message_webhook_id, last_sent_at, last_error, last_error_at FROM scheduled_messages WHERE next_at <= $1 AND enabled = true
`

func (q *Queries) GetDueScheduledMessages(ctx context.Context, nextAt pgtype.Timestamp) ([]ScheduledMessage, error) {
	rows, err := q.db.Query(ctx, getDueScheduledMessages, nextAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledMessage
	for rows.Next() {
		var i ScheduledMessage
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.SavedMessageID,
			&i.Name,
			&i.Description,
			&i.CronExpression,
			&i.OnlyOnce,
			&i.StartAt,
			&i.EndAt,
			&i.NextAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CronTimezone,
			&i.ThreadName,
			&i.MessageWebhookID,
			&i.LastSentAt,
			&i.LastError,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledMessage = `-- name: GetScheduledMessage :one
SELECT id, creator_id, guild_id, channel_id, message_id, saved_message_id, name, description, cron_expression, only_once, start_at, end_at, next_at, enabled, created_at, updated_at, cron_timezone, thread_name, message_webhook_id, last_sent_at, last_error, last_error_at FROM scheduled_messages WHERE id = $1 AND guild_id = $2
`

type GetScheduledMessageParams struct {
	ID      string
	GuildID string
}

func (q *Queries) GetScheduledMessage(ctx context.Context, arg GetScheduledMessageParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, getScheduledMessage, arg.ID, arg.GuildID)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.SavedMessageID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.OnlyOnce,
		&i.StartAt,
		&i.EndAt,
		&i.NextAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CronTimezone,
		&i.ThreadName,
		&i.MessageWebhookID,
		&i.LastSentAt,
		&i.LastError,
		&i.LastErrorAt,
	)
	return i, err
}

const getScheduledMessages = `-- name: GetScheduledMessages :many
SELECT id, creator_id, guild_id, channel_id, message_id, saved_message_id, name, description, cron_expression, only_once, start_at, end_at, next_at, enabled, created_at, updated_at, cron_timezone, thread_name, message_webhook_id, last_sent_at, last_error, last_error_at FROM scheduled_messages WHERE guild_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) GetScheduledMessages(ctx context.Context, guildID string) ([]ScheduledMessage, error) {
	rows, err := q.db.Query(ctx, getScheduledMessages, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledMessage
	for rows.Next() {
		var i ScheduledMessage
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.SavedMessageID,
			&i.Name,
			&i.Description,
			&i.CronExpression,
			&i.OnlyOnce,
			&i.StartAt,
			&i.EndAt,
			&i.NextAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CronTimezone,
			&i.ThreadName,
			&i.MessageWebhookID,
			&i.LastSentAt,
			&i.LastError,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScheduledMessage = `-- name: InsertScheduledMessage :one
INSERT INTO scheduled_messages (
    id, 
    creator_id, 
    guild_id, 
    channel_id, 
    message_id, 
    thread_name, 
    saved_message_id, 
    name, 
    description, 
    cron_expression, 
    cron_timezone, 
    start_at, 
    end_at, 
    next_at, 
    only_once, 
    enabled, 
    created_at, 
    updated_at,
    message_webhook_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, creator_id, guild_id, channel_id, message_id, saved_message_id, name, description, cron_expression, only_once, start_at, end_at, next_at, enabled, created_at, updated_at, cron_timezone, thread_name, message_webhook_id, last_sent_at, last_error, last_error_at
`

type InsertScheduledMessageParams struct {
	ID               string
	CreatorID        string
	GuildID          string
	ChannelID        string
	MessageID        pgtype.Text
	ThreadName       pgtype.Text
	SavedMessageID   string
	Name             string
	Description      pgtype.Text
	CronExpression   pgtype.Text
	CronTimezone     pgtype.Text
	StartAt          pgtype.Timestamp
	EndAt            pgtype.Timestamp
	NextAt           pgtype.Timestamp
	OnlyOnce         bool
	Enabled          bool
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	MessageWebhookID pgtype.Text
}

func (q *Queries) InsertScheduledMessage(ctx context.Context, arg InsertScheduledMessageParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, insertScheduledMessage,
		arg.ID,
		arg.CreatorID,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.ThreadName,
		arg.SavedMessageID,
		arg.Name,
		arg.Description,
		arg.CronExpression,
		arg.CronTimezone,
		arg.StartAt,
		arg.EndAt,
		arg.NextAt,
		arg.OnlyOnce,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MessageWebhookID,
	)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.SavedMessageID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.OnlyOnce,
		&i.StartAt,
		&i.EndAt,
		&i.NextAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CronTimezone,
		&i.ThreadName,
		&i.MessageWebhookID,
		&i.LastSentAt,
		&i.LastError,
		&i.LastErrorAt,
	)
	return i, err
}

const recordScheduledMessageRun = `-- name: RecordScheduledMessageRun :exec
UPDATE scheduled_messages SET
    next_at = $1,
    -- Only ever turns it off, the user may have disabled it while it was sending.
    enabled = enabled AND $2,
    last_sent_at = COALESCE($3, last_sent_at),
    last_error = $4,
    last_error_at = $5,
    updated_at = $6
WHERE id = $7 AND guild_id = $8
`

type RecordScheduledMessageRunParams struct {
	NextAt      pgtype.Timestamp
	Enabled     bool
	LastSentAt  pgtype.Timestamp
	LastError   pgtype.Text
	LastErrorAt pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	ID          string
	GuildID     string
}

func (q *Queries) RecordScheduledMessageRun(ctx context.Context, arg RecordScheduledMessageRunParams) error {
	_, err := q.db.Exec(ctx, recordScheduledMessageRun,
		arg.NextAt,
		arg.Enabled,
		arg.LastSentAt,
		arg.LastError,
		arg.LastErrorAt,
		arg.UpdatedAt,
		arg.ID,
		arg.GuildID,
	)
	return err
}

const updateScheduledMessage = `-- name: UpdateScheduledMessage :one
UPDATE scheduled_messages SET 
    channel_id = $3, 
    message_id = $4, 
    thread_name = $5, 
    saved_message_id = $6, 
    name = $7, 
    description = $8, 
    cron_expression = $9, 
    next_at = $10, 
    start_at = $11, 
    end_at = $12, 
    only_once = $13, 
    enabled = $14, 
    updated_at = $15, 
    cron_timezone = $16,
    message_webhook_id = $17,
    last_error = NULL,
    last_error_at = NULL
WHERE id = $1 AND guild_id = $2 RETURNING id, creator_id, guild_id, channel_id, message_id, saved_message_id, name, description, cron_expression, only_once, start_at, end_at, next_at, enabled, created_at, updated_at, cron_timezone, thread_name, message_webhook_id, last_sent_at, last_error, last_error_at
`

type UpdateScheduledMessageParams struct {
	ID               string
	GuildID          string
	ChannelID        string
	MessageID        pgtype.Text
	ThreadName       pgtype.Text
	SavedMessageID   string
	Name             string
	Description      pgtype.Text
	CronExpression   pgtype.Text
	NextAt           pgtype.Timestamp
	StartAt          pgtype.Timestamp
	EndAt            pgtype.Timestamp
	OnlyOnce         bool
	Enabled          bool
	UpdatedAt        pgtype.Timestamp
	CronTimezone     pgtype.Text
	MessageWebhookID pgtype.Text
}

func (q *Queries) UpdateScheduledMessage(ctx context.Context, arg UpdateScheduledMessageParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, updateScheduledMessage,
		arg.ID,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.ThreadName,
		arg.SavedMessageID,
		arg.Name,
		arg.Description,
		arg.CronExpression,
		arg.NextAt,
		arg.StartAt,
		arg.EndAt,
		arg.OnlyOnce,
		arg.Enabled,
		arg.UpdatedAt,
		arg.CronTimezone,
		arg.MessageWebhookID,
	)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.SavedMessageID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.OnlyOnce,
		&i.StartAt,
		&i.EndAt,
		&i.NextAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CronTimezone,
		&i.ThreadName,
		&i.MessageWebhookID,
		&i.LastSentAt,
		&i.LastError,
		&i.LastErrorAt,
	)
	return i, err
}
