// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CustomBot struct {
	ID                      string
	GuildID                 string
	ApplicationID           string
	Token                   string
	PublicKey               string
	UserID                  string
	UserName                string
	UserDiscriminator       string
	UserAvatar              pgtype.Text
	HandledFirstInteraction bool
	CreatedAt               pgtype.Timestamp
	TokenInvalid            bool
	GatewayStatus           string
	GatewayActivityType     pgtype.Int2
	GatewayActivityName     pgtype.Text
	GatewayActivityState    pgtype.Text
	GatewayActivityUrl      pgtype.Text
}

type CustomCommand struct {
	ID                 string
	GuildID            string
	Name               string
	Description        string
	Enabled            bool
	Parameters         []byte
	Actions            []byte
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	DeployedAt         pgtype.Timestamp
	DerivedPermissions []byte
	LastUsedAt         pgtype.Timestamp
}

type EmbedLink struct {
	ID             string
	Url            string
	ThemeColor     pgtype.Text
	OgTitle        pgtype.Text
	OgSiteName     pgtype.Text
	OgDescription  pgtype.Text
	OgImage        pgtype.Text
	OeType         pgtype.Text
	OeAuthorName   pgtype.Text
	OeAuthorUrl    pgtype.Text
	OeProviderName pgtype.Text
	OeProviderUrl  pgtype.Text
	TwCard         pgtype.Text
	ExpiresAt      pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}

type Entitlement struct {
	ID              string
	UserID          pgtype.Text
	GuildID         pgtype.Text
	UpdatedAt       pgtype.Timestamp
	Deleted         bool
	SkuID           string
	StartsAt        pgtype.Timestamp
	EndsAt          pgtype.Timestamp
	Consumed        bool
	ConsumedGuildID pgtype.Text
}

type Image struct {
	ID              string
	UserID          string
	GuildID         pgtype.Text
	FileHash        string
	FileName        string
	FileSize        int32
	FileContentType string
	S3Key           string
}

type KvEntry struct {
	Key       string
	GuildID   string
	Value     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type MessageActionSet struct {
	ID                 string
	MessageID          string
	SetID              string
	Actions            []byte
	DerivedPermissions []byte
	LastUsedAt         pgtype.Timestamp
	Ephemeral          bool
}

type SavedMessage struct {
	ID          string
	CreatorID   string
	GuildID     pgtype.Text
	UpdatedAt   pgtype.Timestamp
	Name        string
	Description pgtype.Text
	Data        []byte
}

type ScheduledMessage struct {
	ID             string
	CreatorID      string
	GuildID        string
	ChannelID      string
	MessageID      pgtype.Text
	SavedMessageID string
	Name           string
	Description    pgtype.Text
	CronExpression pgtype.Text
	OnlyOnce       bool
	StartAt        pgtype.Timestamp
	EndAt          pgtype.Timestamp
	NextAt         pgtype.Timestamp
	Enabled        bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	CronTimezone   pgtype.Text
	ThreadName     pgtype.Text
}

type Session struct {
	TokenHash   string
	UserID      string
	GuildIds    []string
	AccessToken string
	CreatedAt   pgtype.Timestamp
	ExpiresAt   pgtype.Timestamp
}

type SharedMessage struct {
	ID        string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	Data      []byte
}

type User struct {
	ID            string
	Name          string
	Discriminator string
	Avatar        pgtype.Text
	IsTester      bool
}
