// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: premium_role_assignments.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePremiumRoleAssignment = `-- name: DeletePremiumRoleAssignment :exec
DELETE FROM premium_role_assignments WHERE user_id = $1
`

func (q *Queries) DeletePremiumRoleAssignment(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePremiumRoleAssignment, userID)
	return err
}

const getPremiumRoleAssignments = `-- name: GetPremiumRoleAssignments :many
SELECT user_id FROM premium_role_assignments
`

func (q *Queries) GetPremiumRoleAssignments(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getPremiumRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPremiumRoleAssignment = `-- name: UpsertPremiumRoleAssignment :exec
INSERT INTO premium_role_assignments (user_id, assigned_at) VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type UpsertPremiumRoleAssignmentParams struct {
	UserID     int64
	AssignedAt pgtype.Timestamp
}

func (q *Queries) UpsertPremiumRoleAssignment(ctx context.Context, arg UpsertPremiumRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, upsertPremiumRoleAssignment, arg.UserID, arg.AssignedAt)
	return err
}
