// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, user_id, guild_ids, access_token, created_at, expires_at, refresh_token, token_expires_at, scopes FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.GuildIds,
		&i.AccessToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
	)
	return i, err
}

const getSessionsForUser = `-- name: GetSessionsForUser :many
SELECT token_hash, user_id, guild_ids, access_token, created_at, expires_at, refresh_token, token_expires_at, scopes FROM sessions WHERE user_id = $1
`

func (q *Queries) GetSessionsForUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserID,
			&i.GuildIds,
			&i.AccessToken,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    token_hash,
    user_id,
    guild_ids,
    access_token,
    refresh_token,
    token_expires_at,
    scopes,
    created_at,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING token_hash, user_id, guild_ids, access_token, created_at, expires_at, refresh_token, token_expires_at, scopes
`

type InsertSessionParams struct {
	TokenHash      string
	UserID         string
	GuildIds       []string
	AccessToken    string
	RefreshToken   string
	TokenExpiresAt pgtype.Timestamp
	Scopes         []string
	CreatedAt      pgtype.Timestamp
	ExpiresAt      pgtype.Timestamp
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.GuildIds,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.GuildIds,
		&i.AccessToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
	)
	return i, err
}

const updateSessionTokens = `-- name: UpdateSessionTokens :exec
UPDATE sessions SET access_token = $2, refresh_token = $3, token_expires_at = $4 WHERE token_hash = $1
`

type UpdateSessionTokensParams struct {
	TokenHash      string
	AccessToken    string
	RefreshToken   string
	TokenExpiresAt pgtype.Timestamp
}

func (q *Queries) UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error {
	_, err := q.db.Exec(ctx, updateSessionTokens,
		arg.TokenHash,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	return err
}
