// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: message_action_sets.sql

package postgres

import (
	"context"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const deleteMessageActionSetsForMessage = `-- name: DeleteMessageActionSetsForMessage :exec
DELETE FROM message_action_sets WHERE message_id = $1
`

func (q *Queries) DeleteMessageActionSetsForMessage(ctx context.Context, messageID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageActionSetsForMessage, messageID)
	return err
}

const getMessageActionSet = `-- name: GetMessageActionSet :one
SELECT id, message_id, set_id, actions, derived_permissions, last_used_at, ephemeral FROM message_action_sets WHERE message_id = $1 AND set_id = $2
`

type GetMessageActionSetParams struct {
	MessageID string
	SetID     string
}

func (q *Queries) GetMessageActionSet(ctx context.Context, arg GetMessageActionSetParams) (MessageActionSet, error) {
	row := q.db.QueryRowContext(ctx, getMessageActionSet, arg.MessageID, arg.SetID)
	var i MessageActionSet
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SetID,
		&i.Actions,
		&i.DerivedPermissions,
		&i.LastUsedAt,
		&i.Ephemeral,
	)
	return i, err
}

const getMessageActionSets = `-- name: GetMessageActionSets :many
SELECT id, message_id, set_id, actions, derived_permissions, last_used_at, ephemeral FROM message_action_sets WHERE message_id = $1
`

func (q *Queries) GetMessageActionSets(ctx context.Context, messageID string) ([]MessageActionSet, error) {
	rows, err := q.db.QueryContext(ctx, getMessageActionSets, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageActionSet
	for rows.Next() {
		var i MessageActionSet
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.SetID,
			&i.Actions,
			&i.DerivedPermissions,
			&i.LastUsedAt,
			&i.Ephemeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessageActionSet = `-- name: InsertMessageActionSet :one
INSERT INTO message_action_sets (id, message_id, set_id, actions, derived_permissions, ephemeral) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, message_id, set_id, actions, derived_permissions, last_used_at, ephemeral
`

type InsertMessageActionSetParams struct {
	ID                 string
	MessageID          string
	SetID              string
	Actions            json.RawMessage
	DerivedPermissions pqtype.NullRawMessage
	Ephemeral          bool
}

func (q *Queries) InsertMessageActionSet(ctx context.Context, arg InsertMessageActionSetParams) (MessageActionSet, error) {
	row := q.db.QueryRowContext(ctx, insertMessageActionSet,
		arg.ID,
		arg.MessageID,
		arg.SetID,
		arg.Actions,
		arg.DerivedPermissions,
		arg.Ephemeral,
	)
	var i MessageActionSet
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SetID,
		&i.Actions,
		&i.DerivedPermissions,
		&i.LastUsedAt,
		&i.Ephemeral,
	)
	return i, err
}
