// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: message_action_sets.sql

package postgres

import (
	"context"
	"encoding/json"
)

const deleteMessageActionSetsForMessage = `-- name: DeleteMessageActionSetsForMessage :exec
DELETE FROM message_action_sets WHERE message_id = $1
`

func (q *Queries) DeleteMessageActionSetsForMessage(ctx context.Context, messageID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageActionSetsForMessage, messageID)
	return err
}

const getMessageActionSet = `-- name: GetMessageActionSet :one
SELECT id, message_id, set_id, actions FROM message_action_sets WHERE message_id = $1 AND set_id = $2
`

type GetMessageActionSetParams struct {
	MessageID string
	SetID     string
}

func (q *Queries) GetMessageActionSet(ctx context.Context, arg GetMessageActionSetParams) (MessageActionSet, error) {
	row := q.db.QueryRowContext(ctx, getMessageActionSet, arg.MessageID, arg.SetID)
	var i MessageActionSet
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SetID,
		&i.Actions,
	)
	return i, err
}

const insertMessageActionSet = `-- name: InsertMessageActionSet :one
INSERT INTO message_action_sets (id, message_id, set_id, actions) VALUES ($1, $2, $3, $4) RETURNING id, message_id, set_id, actions
`

type InsertMessageActionSetParams struct {
	ID        string
	MessageID string
	SetID     string
	Actions   json.RawMessage
}

func (q *Queries) InsertMessageActionSet(ctx context.Context, arg InsertMessageActionSetParams) (MessageActionSet, error) {
	row := q.db.QueryRowContext(ctx, insertMessageActionSet,
		arg.ID,
		arg.MessageID,
		arg.SetID,
		arg.Actions,
	)
	var i MessageActionSet
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.SetID,
		&i.Actions,
	)
	return i, err
}
