name: CI (app)

on:
  pull_request:
    paths:
      - "embedg-app/**"
      - ".github/workflows/ci-app.yaml"

jobs:
  typecheck:
    name: embedg-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn install --frozen-lockfile
        working-directory: embedg-app
      - run: ./node_modules/.bin/tsc --noEmit
        working-directory: embedg-app
