name: CI (service)

on:
  pull_request:
    paths:
      - "embedg-service/**"
      - "go.work"
      - "go.work.sum"
      - ".github/workflows/ci-service.yaml"

jobs:
  build:
    name: embedg-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: embedg-service/go.mod
      - run: go build ./... && go vet ./...
        working-directory: embedg-service
